import React, { useState } from 'react';
import { generateProjectIdea } from '../services/geminiService';
import { ProjectBlueprint } from '../types';
import { jsPDF } from "jspdf";
import { useUser } from '../context/UserContext';
import { useSettings } from '../context/SettingsContext';

const Projects: React.FC = () => {
  const { user } = useUser();
  const { openSettings } = useSettings();
  const [project, setProject] = useState<ProjectBlueprint | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
        // Use user's skills if available, otherwise default to a standard stack
        const skillNames = user.skills.length > 0 
            ? user.skills.map(s => s.name) 
            : ['React', 'Node.js', 'PostgreSQL'];
        const level = user.level || 'Intermediate';
        const targetRole = user.targetRole || user.role || "Software Engineer";
        
        // Pass targetRole to ensure project is relevant to career goals
        const result = await generateProjectIdea(targetRole, skillNames, level);
        setProject(result);
    } catch (err: any) {
        console.error(err);
        setError(err.message || "Failed to generate project idea. Check your API key.");
    } finally {
        setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!project) return;
    
    try {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;
        const maxLineWidth = pageWidth - margin * 2;

        // Branding
        doc.setTextColor(23, 84, 207); // Primary Blue
        doc.setFontSize(10);
        doc.text("CAREERPILOT AI PROJECT BLUEPRINT", margin, 15);

        // Title
        doc.setTextColor(17, 19, 24); // Dark Gray
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        const titleLines = doc.splitTextToSize(project.title, maxLineWidth);
        doc.text(titleLines, margin, 25);
        
        let y = 25 + (titleLines.length * 8);

        // Meta Tags
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`${project.difficulty}  |  ${project.techStack.join(', ')}`, margin, y);
        y += 10;

        // Divider
        doc.setDrawColor(230, 230, 230);
        doc.line(margin, y, pageWidth - margin, y);
        y += 10;

        // Description
        doc.setFontSize(11);
        doc.setTextColor(50, 50, 50);
        const descLines = doc.splitTextToSize(project.description, maxLineWidth);
        doc.text(descLines, margin, y);
        y += (descLines.length * 5) + 10;

        // Helper to add sections
        const addSection = (title: string, items: string[], iconChar: string = '•') => {
            if (y > 260) {
                doc.addPage();
                y = 20;
            }
            doc.setFont("helvetica", "bold");
            doc.setFontSize(14);
            doc.setTextColor(17, 19, 24);
            doc.text(title, margin, y);
            y += 8;

            doc.setFont("helvetica", "normal");
            doc.setFontSize(11);
            doc.setTextColor(60, 60, 60);

            items.forEach(item => {
                if (y > 275) {
                    doc.addPage();
                    y = 20;
                }
                const itemText = `${iconChar}  ${item}`;
                const lines = doc.splitTextToSize(itemText, maxLineWidth);
                doc.text(lines, margin, y);
                y += lines.length * 6;
            });
            y += 8;
        };

        addSection("User Stories", project.userStories);
        addSection("Core Features", project.features);
        addSection("Learning Outcomes", project.learningOutcomes);

        doc.save(`CareerPilot_${project.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
    } catch (e) {
        console.error("PDF Download failed", e);
        alert("Failed to download PDF. Please try again.");
    }
  };

  return (
    <div className="w-full max-w-[1200px] mx-auto px-4 py-8">
      <div className="text-center max-w-2xl mx-auto mb-12">
        <h1 className="text-3xl font-extrabold text-gray-900 mb-4">Project Idea Generator</h1>
        <p className="text-gray-500 mb-6">Build your portfolio with context-aware projects generated by AI based on your target role ({user.targetRole || 'Next Level'}).</p>
        <button
            onClick={generate}
            disabled={loading}
            className="px-8 py-3 bg-gradient-to-r from-primary to-blue-600 hover:from-primary-dark hover:to-blue-700 text-white font-bold rounded-full shadow-lg shadow-blue-500/30 transition-all transform hover:-translate-y-1 disabled:opacity-70 flex items-center gap-2 mx-auto"
        >
            {loading ? <span className="material-symbols-outlined animate-spin">sync</span> : <span className="material-symbols-outlined">lightbulb</span>}
            {loading ? 'Designing Project...' : 'Generate New Project'}
        </button>
      </div>
      
      {error && (
        <div className="max-w-2xl mx-auto mb-8 p-4 bg-red-50 border border-red-200 rounded-xl text-red-700 flex flex-col sm:flex-row items-center gap-3">
             <div className="flex items-center gap-3">
                 <span className="material-symbols-outlined">error</span>
                 <div>
                     <p className="font-bold">Generation Failed</p>
                     <p className="text-sm">{error}</p>
                 </div>
             </div>
             <div className="flex gap-2 ml-auto mt-3 sm:mt-0">
                 <button onClick={openSettings} className="px-4 py-2 bg-white border border-red-200 rounded-lg hover:bg-red-50 text-sm font-bold text-red-700 whitespace-nowrap">Update API Key</button>
             </div>
        </div>
      )}

      {project && (
        <div className="animate-fade-in bg-white rounded-2xl border border-gray-200 shadow-xl overflow-hidden">
            <div className="bg-gray-900 p-8 text-white relative overflow-hidden">
                <div className="absolute top-0 right-0 p-12 opacity-10">
                    <span className="material-symbols-outlined text-9xl">architecture</span>
                </div>
                <div className="relative z-10">
                    <div className="flex gap-2 mb-4">
                        <span className="px-3 py-1 bg-white/10 rounded-full text-xs font-bold uppercase border border-white/20">{project.difficulty}</span>
                        {project.techStack.map(tech => (
                            <span key={tech} className="px-3 py-1 bg-blue-500/20 rounded-full text-xs font-bold border border-blue-400/30">{tech}</span>
                        ))}
                    </div>
                    <h2 className="text-3xl font-bold mb-2">{project.title}</h2>
                    <p className="text-gray-300 max-w-3xl text-lg">{project.description}</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 divide-y lg:divide-y-0 lg:divide-x divide-gray-100">
                <div className="p-8">
                    <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-primary">format_list_bulleted</span>
                        User Stories
                    </h3>
                    <ul className="space-y-3">
                        {project.userStories.map((story, i) => (
                            <li key={i} className="flex gap-3 text-sm text-gray-600">
                                <span className="text-primary font-bold">•</span>
                                {story}
                            </li>
                        ))}
                    </ul>
                </div>

                <div className="p-8">
                    <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-purple-600">extension</span>
                        Core Features
                    </h3>
                    <ul className="space-y-3">
                        {project.features.map((feature, i) => (
                            <li key={i} className="flex gap-3 text-sm text-gray-600">
                                <span className="material-symbols-outlined text-purple-500 text-sm">check</span>
                                {feature}
                            </li>
                        ))}
                    </ul>
                </div>

                <div className="p-8 bg-gray-50">
                    <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
                        <span className="material-symbols-outlined text-green-600">school</span>
                        Learning Outcomes
                    </h3>
                    <div className="flex flex-wrap gap-2">
                         {project.learningOutcomes.map((outcome, i) => (
                            <span key={i} className="px-3 py-1.5 bg-white border border-gray-200 rounded-lg text-xs font-semibold text-gray-700 shadow-sm">
                                {outcome}
                            </span>
                        ))}
                    </div>
                    <button 
                        onClick={downloadPDF}
                        className="mt-8 w-full py-2 bg-gray-900 hover:bg-black text-white font-bold rounded-lg transition-colors flex items-center justify-center gap-2 shadow-md hover:shadow-lg"
                    >
                        <span className="material-symbols-outlined">download</span> Download Blueprint
                    </button>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

export default Projects;